#!/usr/bin/python3

def raise_exception():

    a = 5
    b = '5'

    c = a + b
